### Task1

In [11]:
import numpy as np

In [12]:
a = np.array([1, 2, 3, 3, 1])
b = np.array([6, 8, 11, 10, 7])

In [13]:
c = np.vstack((a, b))
c

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [14]:
d = np.transpose(c)
d

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
a = d.copy()

In [16]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Task2

In [17]:
a_centered = np.subtract(a, mean_a)

In [21]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task3

In [25]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])

In [26]:
a_centered_sp

8.0

In [32]:
result = a_centered_sp / (a_centered.shape[0] - 1)
result

2.0